# Generated by Django 4.2.20 on 2025-04-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Глава ТСЖ'), (2, 'Член ТСЖ'), (3, 'Жилец'), (4, 'Специалист')], default=1),
        ),
    ]
