# Generated by Django 4.2.20 on 2025-04-16 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
